<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Privacy Policy - Aavana corporate solutions </title>
		<meta name="description" content="Privacy Policy - Aavana corporate solutions.Always feel safe and secure with the services of aavana.">
		<meta name="keywords" content="Aavana">
		<?php
		include ('header.php');
		?>
	</head>
	<body class="aavana-corporate-page sub-page">
		<div id="main-wrapper">
			<?php
			include ('top-menu.php');
			?>
			<section class="banner-section">
				<div class="container">
					<div class="header-title text-center">
						<h1 class="title">Privacy Policy</h1>
					</div>
				</div>
			</section>
			<section class="aavana-corporate-section call-to-action section-padding">
				<div class="container terms-of-avvana">
					<div class="row">
						<div class="col-md-12">
							<div class="title-bar text-center margin-btm-50">
								<h2 class="title">Privacy Policy</h2>
								<span class="title-border"></span>
							</div>
							<p>
								A privacy policy is a legal document which states all the possible ways that a party gathers, uses, discloses and manages a client’s data and it protects the personal data of client. This privacy policy governs the manner in which Taxraahi.com uses or discloses the information from users (or User) of the https://www.aavana.in/ website. This privacy policy is applicable for the Website and all products and services which are offered by AAVANA.
							</p>

							<ul>
								<li>
									<h5>GENERAL</h5>
									<ul>
										<li>
											This is an electronic record under Information Technology Act, 2000 and all the rules are applicable. The amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This document does not require any physical or digital signature as it is generated by a computer system.
										</li>
										<li>
											Under the provision of Rule 3 (1) of Information Technology Rules 2011, this document is published. It required the publishing of rules and regulations, privacy policy and terms of usage of taxraahi.com
										</li>
										<li>
											The domain name aavana.in (“Website”), is owned and operated by AAVANA CORPORATE SOLUTIONS PVT LTD and having its registered office at No: 41, 2nd floor, 3rd Main, 60 Feet Road, Sanjay Nagar, RMV 2nd Stage, Bengaluru-560094, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.
										</li>
										<li>
											For the purpose of this Privacy Policy (“Policy”), wherever the context so requires,
											Here terms like ‘You’ & ‘User’ are used for any legal person or entity accessing or using the services which are provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872;
											The terms ‘We’, ‘Us’& ‘Our’ shall mean the Website and/or the Company as the context so requires.
											The terms ‘Party’ & ‘Parties’ shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires.
										</li>
										<li>
											The headings are given to each section in this Policy. This is done only for the purpose of organizing the various provisions under this Policy in an orderly manner. The party cannot use it to interpret the provisions contain herein in any manner. Further, it is specifically agreed by the Parties that the headings shall have no legal or contractual value.
										</li>
										<li>
											The user can use the Website which is governed under this Policy as well as the Terms of Use of the Website (“Terms”, available at www.aavana.in), and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. If the User visits the home page of the Website and/or using any of the services which are being provided on the Website shall be deemed to signify the User’s indisputable acceptance of this Policy and the previously mentioned Terms. The User understands and accepts that all Terms and Policy are interconnecting, and that expiry of any of one will lead to the termination of the other.
										</li>

										<li>
											The User indisputably agrees with all the Terms and Policy which legally bind the User and the Company, and that the User shall abide by the rules, guidelines, policies, terms, and conditions applicable to any of the services that are provided by the Website, and that the same is applied with the Terms, and shall be treated as part and parcel of the same. The User understands and accepts that no signature or express act is required to make these Terms and the Policy to bind the User. Under the User’s act, the User can visit any part of the Website with the acceptance of the Policy and the aforementioned Terms.
										</li>
										<li>
											It is agreed by all the parties that a Company/Website has all the rights to make a change in any of the policy and terms mentioned before without any prior notice to User/Users. The User accepts that any change or modification can be made immediately. It is User’s responsibility to keep him/her updated with all the Policy and Terms. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments / modifications made to the Policy and Terms. In so far as the User complies with the Policy and Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter access and use the Website.
										</li>

									</ul>
								</li>
								<p></p>
								<li>
									<h5>COLLECTION OF PERSONAL AND OTHER INFORMATION</h5>
									<ul>

										<li>
											It is being accepted by the User that the personal information is collected and stored by the company, which is provided by the User from time to time on Website but not limited to the User’s username, passwords, email address, name, address, age, date of birth, sex, nationality, shopping preferences, browsing history, etc., as well as any images or other information uploaded/published by the User on the Website. The Website/Company uses this information which is given by the User to provide the services. The User’s need is fulfilled accordingly. This information is used by the Website/Company to improve the portal to make it safer and easier for the User.
										</li>
										<li>
											There is certain information which is tracked automatically by the Company/Website about the User like User’s IP address and User’s behavior on Website. This information can be used by Company/Website to do internal research on user demographics, interests, and behavior, to enable the Company/Website to better understand. The User knows that such information may include the URL that the User visited prior to accessing the Website, the URL which the User subsequently visits (whether or not these URLs form a part of the Website), the User’s computer & web browser information, the User’s IP address, etc.
										</li>
										<li>
											If any User chooses to buy any product or services from the Company/Website, the User is allowing the Company/Website to gather the personal information of the User.
										</li>
										<li>
											The User is aware that if any information which is provided by User whether it is posted message/ review / feedback anywhere on Website can be used by the Company/Website to help out the User in every possible way in future. This retained information can be used to resolve disputes, provide customer support, troubleshoot problems and much other and that such information, if requested, may be provided to judicial or governmental authorities of requisite jurisdiction, or otherwise used by the Company/Website as permitted by applicable laws.
										</li>
										<li>
											All the information whether it is personal or any other like emails or letters or any feedback from other users or third party regarding the User’s activities or posting on Websites is collected or gathered by the company and is compiled in a file or folder by the Company/Website. The User is aware of all this information.
										</li>
										<li>
											A User/Users can browse a website without providing any information to the Website/Company but for certain activities and area, the User has to provide certain information for registration such as placing an order. The User is aware that the information provided to the Company/Website can be used to send the User offers and promotions whether or not based on the User’s previous orders and interests, and the User hereby expressly consents to receive the same.
										</li>
										<li>
											There are certain online surveys which are optional and Company/Website can request the User to complete those surveys. Sometimes these surveys may ask the User to provide the contact information and demographic information (like zip code, age, income bracket, sex, etc.). This data is used to customize the Website for the benefit of the User, and providing all users of the Website with products/services/content that the Company/Website believes they might be interested in availing of, and also to display content according to the User’s preferences, the user is aware about all this.
										</li>
										<li>
											The Company/Website can ask or request the User to provide the reviews for the products/services which are purchased/ availed by the User from Website. The User is aware that such reviews will help other users of the website make prudent and correct purchases, and also help the Company/Website remove sellers whose products are unsatisfactory in any way, and the User hereby expressly authorizes the Company/Website to publish any and all reviews written by the User on the Website, along with the User’s name and certain contact details, for the benefit and use of other Users of the Website.
										</li>
										<li>
											The information like content/reviews/surveys/feedback which is submitted by the User to Company/Website cannot be a store, upload, publish or display in any manner. The User authorizes the Website/Company to remove any such content, review, survey or feedback from Website which has been submitted by User, without cause or being required to notify the User of the same.
										</li>
									</ul>
								</li>
								<p></p>
								<li>
									<h5>COOKIES</h5>
									<ul>
										<li>
											A cookie is an information which is being stored on hard disk by Website so that it can remember something about the User later time. The User is aware that this information that is Cookie is stored by the Website/Company to use it later if required and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User’s login identification, password, etc. Web site installs permanent and temporary cookies in User’s hard disk and browser and the User is aware of it and does hereby expressly consent to the same.
										</li>
										<li>
											There are many data collection devices such as cookies on certain pages of the Website. These devices help in analyzing the web page flow, measure promotional effectiveness and promote trust and safety. These are the features which are only available due to the use of cookies. The User is aware of all this. While the User is free to decline the Website’s cookies if the User’s browser permits, the User may consequently be unable to use certain features on the Website.
										</li>
										<li>
											Beside this, the User is aware that He/she might face other data collection devices like cookies on certain pages which are installed by third parties or affiliates on the Website. The User knows and accepts that the website/Company is not responsible as they do not control the use of such cookies/other devices by third parties and the User assumes any and all risks in this regard.
										</li>
									</ul>
								</li>
								<p></p>
								<li>
									<h5>SHARING OF PERSONAL INFORMATION</h5>
									<ul>
										<li>
											The Website/Company can share the personal information of User to detect and prevent identity theft, fraud, and other illegal acts. This information can be shared with corporate entities and affiliates to help them; correlate related or multiple accounts to prevent abuse of the Website’s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity. The User is aware of it.
										</li>
										<li>
											The Website/Company has right to disclose the personal information of User if required to do so by law or if the Website/Company believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. This information can also be disclosed to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or another content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.
										</li>
										<li>
											If a Company/Website is merging with other Company/Website or in the event the of reorganization, amalgamation or reconstructing of the Company’s business, the Company/Website can share the personal information of User if required. Such business entity or new entity will continue to be bound be the Terms and Policy, as may be amended from time to time.
										</li>
									</ul>
								</li>
								<p></p>
								<li>
									<h5>SECURITY</h5>
									<p>
										All the transactions which are made on the Website are secure and protected. No information is disclosed while making the transaction on the Website as it is encrypted to protect the User against unintentional disclosure to third parties. Any information related to the User’s credit and debit card information is not received, stored by or retained by the Company / Website in any manner. This information is provided by the User directly to the payment gateway which is authorized to handle the information provided and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.
									</p>
								</li>
								<p></p>
								<li>
									<h5>THIRD PARTY ADVERTISEMENTS / PROMOTIONS</h5>
									<ul>
										<p>
											The third-party advertising companies are used to serve ads to the users of the Website. These companies may use the information related to the User’s visit to the Website and other websites in order to provide advertisements to the User. The Website may contain links to other websites also that may collect personal information about the User. The Company/Website is not at all responsible for the privacy or the content of any of the linked websites. The User agrees that the risks associated will be borne entirely by the User.
										</p>
									</ul>
								</li>
								<li>
									<h5>USER’S CONSENT</h5>
									<p>
										By using the Website and/ or by providing information to the Company through the Website, the User consents to the collection and use of the information disclosed by the User on the Website in accordance with this Policy, including but not limited to the User’s consent the Company/Website sharing/divulging the User’s information, as per the terms contained here in above in Section 4 of the Policy.
									</p>
								</li>
								<li>
									<h5>DISPUTE RESOLUTION AND JURISDICTION</h5>
									<p>
										Any dispute related to formation, interpretation and performance of this Policy will be solved through a two-step Alternate Dispute Resolution (“ADR”) mechanism. It is agreed by the Parties. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Policy and/or Terms.
									</p>
									<ul>
										<li>
											Mediation: If there would be any dispute between the parties, the Parties will attempt to resolve the dispute amongst themselves, with the mutual satisfaction of both Parties. If the Parties are unable to resolve the dispute between themselves within the period of thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below;
										</li>
										<li>
											Arbitration: If the Parties are unable to resolve the dispute between them through Mediation, then it will be transferred forward to the Arbitration by a sole arbitrator to be appointed by the Company. The order passed by the sole arbitrator will be valid and binding on both Parties. The costs of proceedings will be beard by the Parties, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Delhi, India.
										</li>
									</ul>
								</li>
								<p>
									The Terms, Policy and any other agreements between the Parties are governed by the laws, rules and regulations of India and it is agreed by the Parties. The Courts at Delhi shall have exclusive jurisdiction over any disputes arising between the Parties.
								</p>

							</ul>
						</div>
					</div>
				</div>
			</section>
		</div>
		<?php
		include ('footer.php');
		?>
	</body>
</html>

